apiVersion: apps/v1
kind: Deployment
metadata:
  name: green1
spec:
  replicas: 4
  template:
    metadata:
      name: nginxpod4jenkins
      labels:
        app: green
    spec:
      containers:
        - name: cont
          image: nginx
  selector:
    matchLabels:
      app: green
