apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentinyaml12
  labels:
    color: blue
    app: erp
spec:
  replicas: 3
  template:
    metadata:
      name: deploymentpodinyamlusingjenkins123
      labels:
        app: love
    spec:
     containers:
       - name: deploymentcontainerinyamlusingjenkins
         image: nginx
  selector:
    matchLabels:
      app: love
